In [0]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

In [3]:
hello = tf.constant('Hello, Tensorflow')
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
hello = tf.constant(1)
hello

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
num1 = tf.constant(10)
num2 = tf.constant(20)
num3 = tf.add(num1, num2)
num3

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [8]:
tensor = tf.constant(-1.0, shape=[2, 3])
tensor

<tf.Tensor 'Const_4:0' shape=(2, 3) dtype=float32>

In [9]:
sess = tf.Session()
sess.run(hello)

1

In [10]:
tensorX = tf.placeholder(tf.float32, [None, 2])
type(tensorX)

tensorflow.python.framework.ops.Tensor

In [11]:
tensorX

<tf.Tensor 'Placeholder:0' shape=(?, 2) dtype=float32>

In [0]:
x_data = [[1,1],[2,2]]

In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [14]:
sess.run(tensorX, feed_dict={tensorX:x_data})

array([[1., 1.],
       [2., 2.]], dtype=float32)

In [0]:
sess.close()

In [16]:
tf.random_normal([3,2])

<tf.Tensor 'random_normal:0' shape=(3, 2) dtype=float32>

In [0]:
tensorX = tf.placeholder(tf.float32, [None,2])

W = tf.Variable(tf.random_normal([2,2]))
b = tf.Variable(tf.random_normal([2,1]))


In [18]:
print(W)
print(b)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float32_ref>


In [0]:
expr = tf.matmul(tensorX, W) + b

In [20]:
expr

<tf.Tensor 'add_1:0' shape=(2, 2) dtype=float32>

In [25]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(x_data)
print(sess.run(W))
print(sess.run(b))
print(sess.run(expr, feed_dict={tensorX:x_data}))
sess.close()

[[1, 1], [2, 2]]
[[-0.68215597  0.43459925]
 [-1.2393247   0.37210718]]
[[-1.0545598]
 [-0.5132055]]
[[-2.9760404 -0.2478534]
 [-4.356167   1.1002073]]


In [47]:
mnist = tf.keras.datasets.mnist
mnist

<module 'tensorflow.python.keras.api._v1.keras.datasets.mnist' from '/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/api/_v1/keras/datasets/mnist/__init__.py'>

In [0]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [49]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [50]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [51]:
y_train[0:3]

array([5, 0, 4], dtype=uint8)

In [0]:
X_train, X_test= X_train/255.0, X_test/255.0 ## 정규화

In [0]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),  #입력노드 개수 28*28
    tf.keras.layers.Dense(512, activation=tf.nn.relu),  #은닉층 노드 개수 512개, 활성함수 relu
    tf.keras.layers.Dropout(0,2),  
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)  #결과층 노드 개수 10개, 활성함수 softmax
])

In [0]:
model.compile(optimizer='adam',   #최적화
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [55]:
model.fit(X_train, y_train, epochs=5)  #5번 학습

Epoch 1/5
60000/60000 [==============================] - 9s 147us/sample - loss: 0.2006 - acc: 0.9415
Epoch 2/5
60000/60000 [==============================] - 8s 140us/sample - loss: 0.0822 - acc: 0.9750
Epoch 3/5
60000/60000 [==============================] - 8s 137us/sample - loss: 0.0526 - acc: 0.9836
Epoch 4/5
60000/60000 [==============================] - 8s 136us/sample - loss: 0.0381 - acc: 0.9878
Epoch 5/5
60000/60000 [==============================] - 8s 137us/sample - loss: 0.0278 - acc: 0.9909


In [56]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 1s 55us/sample - loss: 0.0667 - acc: 0.9809


[0.06673652003596363, 0.9809]