In [1]:
import tensorflow as tf
import numpy as np

In [3]:
import os, warnings
import tensorflow as tf
import time
from IPython.display import display, Image

In [4]:
warnings.filterwarnings(action='ignore')

In [5]:
char_arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g',
'h', 'i', 'j', 'k', 'l', 'm', 'n',
'o', 'p', 'q', 'r', 's', 't', 'u',
'v', 'w', 'x', 'y', 'z']

In [6]:
num_dic = {n: i for i, n in enumerate(char_arr)}
dic_len = len(num_dic)
print(dic_len)

26


In [7]:
seq_data = ['word', 'wood', 'deep', 'dive',
'cold', 'cool', 'load', 'love', 'kiss', 'kind']

In [8]:
print([num_dic[n] for n in seq_data[0][:-1]])
print(np.eye(dic_len)[[22, 14, 17]])

[22, 14, 17]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0.]]


In [9]:
def make_batch(seq_data, dic_len_num):
    input_batch = []
    target_batch = []
    for seq in seq_data:
# input은 단어의 글자 알파벳 배열의 인덱스 번호 입니다.
# [22, 14, 17] [22, 14, 14] [3, 4, 4] [3, 8, 21] ...
        input = [num_dic[n] for n in seq[:-1]]
        target = num_dic[seq[-1]] # 마지막 글자 인덱스
# 3글자에 대한 one-hot 인코딩을 합니다.
# if input is [0, 1, 2]:
# [[ 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# [ 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
# [ 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
        input_batch.append(np.eye(dic_len_num)[input])
        target_batch.append(target)
    return input_batch, target_batch

In [10]:
seq_data_test = ['work', 'book']

In [16]:
a, b= make_batch(seq_data_test, dic_len)
print("a의 값 : 3글자의 알파벳 인덱스 원핫값\n") # w, o, r
print("전체 단어수 : {}\n".format(len(a)))
print("첫번째 단어 3글자 :")
print(a[0]) # w, o, r
print("두번째 단어 3글자 :")
print(a[1]) # b, o, o
print("b의 값 : 마지막 글자 index") # k, k
print(b) # d
print("a와 b의 리스트 길이") # k, k
print(len(a), len(b)) # d

a의 값 : 3글자의 알파벳 인덱스 원핫값

전체 단어수 : 2

첫번째 단어 3글자 :
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0.]]
두번째 단어 3글자 :
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
b의 값 : 마지막 글자 index
[10, 10]
a와 b의 리스트 길이
2 2


In [12]:
learning_rate = 0.01
n_hidden = 128
total_epoch = 30
n_step = 3
n_input = n_class = dic_len

In [17]:
X = tf.placeholder(tf.float32, [None, n_step, n_input]) # 입력
Y = tf.placeholder(tf.int32, [None]) # 출력
W = tf.Variable(tf.random_normal([n_hidden, n_class]))
b = tf.Variable(tf.random_normal([n_class]))

In [18]:
cell1 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden) # 첫번째 셀 생성
cell1 = tf.nn.rnn_cell.DropoutWrapper(cell1, output_keep_prob=0.5) # Dropout
cell2 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden) # 두번째 셀 생성

W1030 16:41:30.493389   232 deprecation.py:323] From <ipython-input-18-bc40387c5c6a>:1: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.


In [20]:
# 에러 발생시 커널 restart
multi_cell = tf.nn.rnn_cell.MultiRNNCell([cell1, cell2]) # 멀티 셀 생성.
outputs, states = tf.nn.dynamic_rnn(multi_cell, X, dtype=tf.float32) 
# RNN신경망

W1030 16:41:52.076076   232 deprecation.py:323] From <ipython-input-20-2ad9768e99fd>:2: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
W1030 16:41:52.077975   232 deprecation.py:323] From <ipython-input-20-2ad9768e99fd>:3: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W1030 16:41:52.574114   232 deprecation.py:506] From C:\Python\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to th

In [21]:
print("multi_cell ======>")
print(multi_cell)
print()
print("outputs ======>")
print(outputs)
print()
print("states ======>")
print(states)

multi_cell ======>

outputs ======>
Tensor("rnn/transpose_1:0", shape=(?, 3, 128), dtype=float32)

states ======>
(LSTMStateTuple(c=<tf.Tensor 'rnn/while/Exit_3:0' shape=(?, 128) dtype=float32>, h=<tf.Tensor 'rnn/while/Exit_4:0' shape=(?, 128) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'rnn/while/Exit_5:0' shape=(?, 128) dtype=float32>, h=<tf.Tensor 'rnn/while/Exit_6:0' shape=(?, 128) dtype=float32>))


In [22]:
outputs = tf.transpose(outputs, [1, 0, 2])
outputs = outputs[-1]
model = tf.matmul(outputs, W) + b

In [24]:
cost = tf.reduce_mean(
            tf.nn.sparse_softmax_cross_entropy_with_logits(
                logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [25]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
input_batch, target_batch = make_batch(seq_data, dic_len)

In [26]:
for epoch in range(total_epoch):
    _, loss = sess.run([optimizer, cost],
                        feed_dict={X: input_batch, Y: target_batch})
    print('Epoch:', '%04d' % (epoch + 1),
            'cost =', '{:.6f}'.format(loss))
print('최적화 완료!')

Epoch: 0001 cost = 3.220035
Epoch: 0002 cost = 2.331971
Epoch: 0003 cost = 1.350989
Epoch: 0004 cost = 1.132795
Epoch: 0005 cost = 0.930337
Epoch: 0006 cost = 0.473265
Epoch: 0007 cost = 0.522298
Epoch: 0008 cost = 0.380008
Epoch: 0009 cost = 0.326321
Epoch: 0010 cost = 0.230560
Epoch: 0011 cost = 0.133499
Epoch: 0012 cost = 0.266808
Epoch: 0013 cost = 0.265052
Epoch: 0014 cost = 0.095857
Epoch: 0015 cost = 0.055672
Epoch: 0016 cost = 0.188474
Epoch: 0017 cost = 0.487413
Epoch: 0018 cost = 0.021052
Epoch: 0019 cost = 0.111372
Epoch: 0020 cost = 0.102897
Epoch: 0021 cost = 0.020141
Epoch: 0022 cost = 0.197268
Epoch: 0023 cost = 0.160847
Epoch: 0024 cost = 0.008887
Epoch: 0025 cost = 0.063560
Epoch: 0026 cost = 0.045201
Epoch: 0027 cost = 0.103657
Epoch: 0028 cost = 0.075440
Epoch: 0029 cost = 0.079054
Epoch: 0030 cost = 0.183254
최적화 완료!


In [27]:
# 레이블값이 정수이므로 예측값도 정수로 변경해줍니다.
prediction = tf.cast(tf.argmax(model, 1), tf.int32)
print("prediction : ", prediction)
# one-hot 인코딩이 아니므로 입력값을 그대로 비교합니다.
prediction_check = tf.equal(prediction, Y)
accuracy = tf.reduce_mean(tf.cast(prediction_check, tf.float32))
print("accuracy : ", accuracy)

prediction :  Tensor("Cast:0", shape=(?,), dtype=int32)
accuracy :  Tensor("Mean_1:0", shape=(), dtype=float32)


In [28]:
seq_data_test = ['hard', 'okay', 'deep', 'live',
'call', 'cool', 'load', 'love', 'kiss', 'kind']

In [30]:
input_batch, target_batch = make_batch(seq_data_test, dic_len)
predict, accuracy_val = sess.run([prediction, accuracy],
                                feed_dict={X: input_batch, Y: target_batch})
print(predict, accuracy_val)

[ 3  3 15  4  3 11  3  4 18  3] 0.8


In [31]:
predict_words = []
for idx, val in enumerate(seq_data_test):
    last_char = char_arr[predict[idx]]
    predict_words.append(val[:3] + last_char)
print('\n=== 예측 결과 ===')
print('입력값:', [w[:3] + ' ' for w in seq_data_test])
print('예측값:', predict_words)
print('정확도:', accuracy_val)


=== 예측 결과 ===
입력값: ['har ', 'oka ', 'dee ', 'liv ', 'cal ', 'coo ', 'loa ', 'lov ', 'kis ', 'kin ']
예측값: ['hard', 'okad', 'deep', 'live', 'cald', 'cool', 'load', 'love', 'kiss', 'kind']
정확도: 0.8
