In [3]:
import tensorflow as tf
from IPython.display import Image 
from tqdm import tqdm_notebook

In [4]:
tf.set_random_seed(777) 

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]  
y_data = [[0], [0], [0], [1], [1], [1]]                     

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [5]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(10001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0 or step < 10 :
            print("Step : {} \t Cost : {}".format(step, cost_val))
            
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})

Step : 0 	 Cost : 1.7307828664779663
Step : 1 	 Cost : 1.7099443674087524
Step : 2 	 Cost : 1.689176082611084
Step : 3 	 Cost : 1.6684807538986206
Step : 4 	 Cost : 1.6478619575500488
Step : 5 	 Cost : 1.6273231506347656
Step : 6 	 Cost : 1.6068668365478516
Step : 7 	 Cost : 1.5864981412887573
Step : 8 	 Cost : 1.5662189722061157
Step : 9 	 Cost : 1.5460346937179565
Step : 200 	 Cost : 0.5715118050575256
Step : 400 	 Cost : 0.507413923740387
Step : 600 	 Cost : 0.47182419896125793
Step : 800 	 Cost : 0.44758477807044983
Step : 1000 	 Cost : 0.42857101559638977
Step : 1200 	 Cost : 0.41232457756996155
Step : 1400 	 Cost : 0.39775514602661133
Step : 1600 	 Cost : 0.3843379020690918
Step : 1800 	 Cost : 0.37180110812187195
Step : 2000 	 Cost : 0.35999321937561035
Step : 2200 	 Cost : 0.34882208704948425
Step : 2400 	 Cost : 0.33822622895240784
Step : 2600 	 Cost : 0.3281605541706085
Step : 2800 	 Cost : 0.31858906149864197
Step : 3000 	 Cost : 0.3094808757305145
Step : 3200 	 Cost : 0.300

In [6]:
print("# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}".
      format(
    h = h, c = c, a = a
))

# Hypothesis: 
[[0.03074026]
 [0.15884683]
 [0.3048674 ]
 [0.78138196]
 [0.93957496]
 [0.9801688 ]] 

# Correct (Y): 
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 1.0


In [9]:
import pandas as pd

df = pd.read_csv("./data/data-03-diabetes.csv", header=None)
df.head(10)

0         1         2         3         4         5         6  \
0 -0.294118  0.487437  0.180328 -0.292929  0.000000  0.001490 -0.531170   
1 -0.882353 -0.145729  0.081967 -0.414141  0.000000 -0.207153 -0.766866   
2 -0.058824  0.839196  0.049180  0.000000  0.000000 -0.305514 -0.492741   
3 -0.882353 -0.105528  0.081967 -0.535354 -0.777778 -0.162444 -0.923997   
4  0.000000  0.376884 -0.344262 -0.292929 -0.602837  0.284650  0.887276   
5 -0.411765  0.165829  0.213115  0.000000  0.000000 -0.236960 -0.894962   
6 -0.647059 -0.216080 -0.180328 -0.353535 -0.791962 -0.076006 -0.854825   
7  0.176471  0.155779  0.000000  0.000000  0.000000  0.052161 -0.952178   
8 -0.764706  0.979899  0.147541 -0.090909  0.283688 -0.090909 -0.931682   
9 -0.058824  0.256281  0.573770  0.000000  0.000000  0.000000 -0.868488   

          7  8  
0 -0.033333  0  
1 -0.666667  1  
2 -0.633333  0  
3  0.000000  1  
4 -0.600000  0  
5 -0.700000  1  
6 -0.833333  0  
7 -0.733333  1  
8  0.066667  0  
9  0.100000  0

In [10]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  

xy = np.loadtxt('./data/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(" x_data.shape : {x_shape} \n y_data.shape : {y_shape}".format(
        x_shape = x_data.shape, 
        y_shape = y_data.shape
    ))

X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

 x_data.shape : (759, 8) 
 y_data.shape : (759, 1)


In [11]:
print(len(xy)) 
xy[:10]

759


array([[-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
         0.00149028, -0.53117   , -0.0333333 ,  0.        ],
       [-0.882353  , -0.145729  ,  0.0819672 , -0.414141  ,  0.        ,
        -0.207153  , -0.766866  , -0.666667  ,  1.        ],
       [-0.0588235 ,  0.839196  ,  0.0491803 ,  0.        ,  0.        ,
        -0.305514  , -0.492741  , -0.633333  ,  0.        ],
       [-0.882353  , -0.105528  ,  0.0819672 , -0.535354  , -0.777778  ,
        -0.162444  , -0.923997  ,  0.        ,  1.        ],
       [ 0.        ,  0.376884  , -0.344262  , -0.292929  , -0.602837  ,
         0.28465   ,  0.887276  , -0.6       ,  0.        ],
       [-0.411765  ,  0.165829  ,  0.213115  ,  0.        ,  0.        ,
        -0.23696   , -0.894962  , -0.7       ,  1.        ],
       [-0.647059  , -0.21608   , -0.180328  , -0.353535  , -0.791962  ,
        -0.0760059 , -0.854825  , -0.833333  ,  0.        ],
       [ 0.176471  ,  0.155779  ,  0.        ,  0.        ,  0

In [12]:
print(len(x_data)) 
x_data[:10]

759


array([[-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
         0.00149028, -0.53117   , -0.0333333 ],
       [-0.882353  , -0.145729  ,  0.0819672 , -0.414141  ,  0.        ,
        -0.207153  , -0.766866  , -0.666667  ],
       [-0.0588235 ,  0.839196  ,  0.0491803 ,  0.        ,  0.        ,
        -0.305514  , -0.492741  , -0.633333  ],
       [-0.882353  , -0.105528  ,  0.0819672 , -0.535354  , -0.777778  ,
        -0.162444  , -0.923997  ,  0.        ],
       [ 0.        ,  0.376884  , -0.344262  , -0.292929  , -0.602837  ,
         0.28465   ,  0.887276  , -0.6       ],
       [-0.411765  ,  0.165829  ,  0.213115  ,  0.        ,  0.        ,
        -0.23696   , -0.894962  , -0.7       ],
       [-0.647059  , -0.21608   , -0.180328  , -0.353535  , -0.791962  ,
        -0.0760059 , -0.854825  , -0.833333  ],
       [ 0.176471  ,  0.155779  ,  0.        ,  0.        ,  0.        ,
         0.052161  , -0.952178  , -0.733333  ],
       [-0.764706  ,  0.979899  

In [13]:
print(len(y_data)) 
y_data[:10]

759


array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [14]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(10001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})       
        if step % 200 == 0 or step < 10 :
            print("Step : {} \t Cost : {}".format(step, cost_val))    

    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    

Step : 0 	 Cost : 0.9742220044136047
Step : 1 	 Cost : 0.9717562198638916
Step : 2 	 Cost : 0.9693101644515991
Step : 3 	 Cost : 0.966883659362793
Step : 4 	 Cost : 0.964477002620697
Step : 5 	 Cost : 0.9620894193649292
Step : 6 	 Cost : 0.9597210884094238
Step : 7 	 Cost : 0.9573723077774048
Step : 8 	 Cost : 0.9550420045852661
Step : 9 	 Cost : 0.9527310729026794
Step : 200 	 Cost : 0.7338058352470398
Step : 400 	 Cost : 0.6805428862571716
Step : 600 	 Cost : 0.6573832035064697
Step : 800 	 Cost : 0.6405060887336731
Step : 1000 	 Cost : 0.6259894967079163
Step : 1200 	 Cost : 0.6130377650260925
Step : 1400 	 Cost : 0.601396381855011
Step : 1600 	 Cost : 0.5909146070480347
Step : 1800 	 Cost : 0.5814695358276367
Step : 2000 	 Cost : 0.5729514360427856
Step : 2200 	 Cost : 0.5652616620063782
Step : 2400 	 Cost : 0.5583115220069885
Step : 2600 	 Cost : 0.5520215034484863
Step : 2800 	 Cost : 0.5463204383850098
Step : 3000 	 Cost : 0.5411451458930969
Step : 3200 	 Cost : 0.53643953800201

In [15]:
print('# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}'.
      format(h=h[:20], c=c[:20], a=a))

# Hypothesis: 
[[0.37003186]
 [0.9154805 ]
 [0.21602729]
 [0.9483494 ]
 [0.08354768]
 [0.7647524 ]
 [0.94660914]
 [0.6240098 ]
 [0.24575189]
 [0.53068644]
 [0.7005221 ]
 [0.17214665]
 [0.16543275]
 [0.2199429 ]
 [0.71247756]
 [0.45385256]
 [0.73282206]
 [0.86161494]
 [0.8147425 ]
 [0.5555971 ]] 

# Correct (Y): 
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 0.7667984366416931
