In [1]:
from IPython.display import Image 
from numpy.random import randn
import numpy as np

In [2]:
data = randn(2, 3)
data

array([[-1.16569572,  0.9533428 ,  1.06485181],
       [ 0.44993966, -0.32214417, -0.01925571]])

In [8]:
data * 2

array([[-2.33139143,  1.9066856 ,  2.12970361],
       [ 0.89987932, -0.64428834, -0.03851141]])

In [4]:
data + data

array([[-2.33139143,  1.9066856 ,  2.12970361],
       [ 0.89987932, -0.64428834, -0.03851141]])

In [5]:
data

array([[-1.16569572,  0.9533428 ,  1.06485181],
       [ 0.44993966, -0.32214417, -0.01925571]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((4, 3, 2))   # 차원, 행, 열

array([[[6.23042070e-307, 3.56043053e-307],
        [1.37961641e-306, 1.33508845e-306],
        [1.33511969e-306, 6.23037996e-307]],

       [[6.23053954e-307, 9.34609790e-307],
        [8.45593934e-307, 9.34600963e-307],
        [1.86921143e-306, 6.23061763e-307]],

       [[2.22522053e-306, 1.11261095e-306],
        [6.89804132e-307, 8.45610231e-307],
        [9.34601642e-307, 6.89804132e-307]],

       [[2.22522053e-306, 9.34609111e-307],
        [2.22522597e-306, 1.33511969e-306],
        [8.34426039e-308, 2.10081501e-312]]])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [23]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [29]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
# numeric_strings.astype(float)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [30]:
# numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [31]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [33]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [35]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [37]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [39]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5]

5

In [42]:
arr[5:8]

array([5, 6, 7])

In [43]:
arr[5:8] = 12

In [44]:
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [45]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [46]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [47]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [51]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [52]:
arr2d[0][2]

3

In [53]:
arr2d[0, 2]

3

In [54]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d[1, 0]

array([7, 8, 9])

In [60]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [62]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr2d[1, :2]

array([4, 5])

In [67]:
arr2d[2, :1]

array([7])

In [69]:
arr2d[:2, 1:] = 0

In [70]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [72]:
data = randn(7, 4)
data

array([[-0.94435469,  2.09963964,  0.16856607, -1.25541399],
       [ 0.86089339, -0.53829981, -0.11257567,  0.88827624],
       [-0.21009252,  1.08627985,  0.01732025, -1.15831526],
       [ 0.76650708,  0.89626344,  0.80531939,  0.38550955],
       [ 0.08816043,  1.95531141, -0.60651135, -0.96915383],
       [ 0.11158861, -1.15795618,  1.01487227, -0.07343134],
       [ 1.02995813, -0.80887801,  0.97649566,  4.04585192]])

In [73]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [74]:
data[names == 'Bob'] # 첫 번째 행, 네 번째 행

array([[-0.94435469,  2.09963964,  0.16856607, -1.25541399],
       [ 0.76650708,  0.89626344,  0.80531939,  0.38550955]])

In [75]:
data[names == 'Bob', 2:]   #첫, 네 번째 행, 2~ 열

array([[ 0.16856607, -1.25541399],
       [ 0.80531939,  0.38550955]])

In [76]:
data[names == 'Bob', 3]  # "" , 마지막 열

array([-1.25541399,  0.38550955])

In [77]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [78]:
data[names != 'Bob']    

array([[ 0.86089339, -0.53829981, -0.11257567,  0.88827624],
       [-0.21009252,  1.08627985,  0.01732025, -1.15831526],
       [ 0.08816043,  1.95531141, -0.60651135, -0.96915383],
       [ 0.11158861, -1.15795618,  1.01487227, -0.07343134],
       [ 1.02995813, -0.80887801,  0.97649566,  4.04585192]])

In [79]:
data[names != 'Bob', 1:]

array([[-0.53829981, -0.11257567,  0.88827624],
       [ 1.08627985,  0.01732025, -1.15831526],
       [ 1.95531141, -0.60651135, -0.96915383],
       [-1.15795618,  1.01487227, -0.07343134],
       [-0.80887801,  0.97649566,  4.04585192]])

In [80]:
data[names != 'Bob', 0]

array([ 0.86089339, -0.21009252,  0.08816043,  0.11158861,  1.02995813])

In [81]:
data[~(names == 'Bob')]

array([[ 0.86089339, -0.53829981, -0.11257567,  0.88827624],
       [-0.21009252,  1.08627985,  0.01732025, -1.15831526],
       [ 0.08816043,  1.95531141, -0.60651135, -0.96915383],
       [ 0.11158861, -1.15795618,  1.01487227, -0.07343134],
       [ 1.02995813, -0.80887801,  0.97649566,  4.04585192]])

In [82]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [83]:
data[mask]

array([[-0.94435469,  2.09963964,  0.16856607, -1.25541399],
       [-0.21009252,  1.08627985,  0.01732025, -1.15831526],
       [ 0.76650708,  0.89626344,  0.80531939,  0.38550955],
       [ 0.08816043,  1.95531141, -0.60651135, -0.96915383]])

In [84]:
data[data < 0] = 0
data

array([[0.        , 2.09963964, 0.16856607, 0.        ],
       [0.86089339, 0.        , 0.        , 0.88827624],
       [0.        , 1.08627985, 0.01732025, 0.        ],
       [0.76650708, 0.89626344, 0.80531939, 0.38550955],
       [0.08816043, 1.95531141, 0.        , 0.        ],
       [0.11158861, 0.        , 1.01487227, 0.        ],
       [1.02995813, 0.        , 0.97649566, 4.04585192]])

In [85]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.86089339, 0.        , 0.        , 0.88827624],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.11158861, 0.        , 1.01487227, 0.        ],
       [1.02995813, 0.        , 0.97649566, 4.04585192]])

In [86]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [87]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [88]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [91]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [92]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [93]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [94]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [96]:
arr = np.random.randn(6,3)
arr

array([[ 0.25040073,  0.96295339, -0.42537459],
       [-0.49856296,  1.14247288,  0.17491541],
       [-0.00638899, -0.62559882,  1.21695537],
       [ 1.10231659, -0.38849453,  0.61137813],
       [-1.75820935, -1.23464985,  0.76920468],
       [-1.11871902, -0.48439685, -0.20635579]])

In [97]:
np.dot(arr.T, arr)

array([[ 5.8692406 ,  1.95995943, -0.64913203],
       [ 1.95995943,  4.53382597, -2.05836305],
       [-0.64913203, -2.05836305,  2.7005611 ]])

In [98]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [100]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [101]:
?arr.swapaxes

In [102]:
?arr.dot