In [1]:
from IPython.display import Image 
from tqdm import tqdm_notebook


In [2]:
import tensorflow as tf
import numpy as np

In [4]:
tf.set_random_seed(777)

x_data = [[10,5],[9,5],[3,2],[2,4],[11,1]]
y_data = [[1,0,0],
         [1,0,0],
         [0,1,0],
         [0,1,0],
         [0,0,1]]

X = tf.placeholder('float', [None, 2])
Y = tf.placeholder('float', [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([2, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)


In [5]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
        print('Step : {}, \t Cost : {}'.format(step, sess.run(cost, 
                                                              feed_dict={X:x_data, Y : y_data})))

Step : 0, 	 Cost : 5.044024467468262
Step : 200, 	 Cost : 0.1112934798002243
Step : 400, 	 Cost : 0.05863405019044876
Step : 600, 	 Cost : 0.03917425870895386
Step : 800, 	 Cost : 0.029238993301987648
Step : 1000, 	 Cost : 0.02326115593314171
Step : 1200, 	 Cost : 0.019285501912236214
Step : 1400, 	 Cost : 0.01645708829164505
Step : 1600, 	 Cost : 0.014344898983836174
Step : 1800, 	 Cost : 0.012708926573395729
Step : 2000, 	 Cost : 0.011405272409319878



In [7]:
test_data = [[9.5, 5.5], 
             [9.9, 1.5], 
             [3.1, 2.1]]

pred_val = sess.run(hypothesis, feed_dict={X: test_data})
pred_idx = sess.run(tf.argmax(pred_val, 1))

print("test data : {} \n\npredict value : \n {} \n\npredict index : {}".format(test_data, pred_val, pred_idx))

test data : [[9.5, 5.5], [9.9, 1.5], [3.1, 2.1]] 

predict value : 
 [[9.89088714e-01 1.07102245e-02 2.01088653e-04]
 [2.56168693e-02 3.51882647e-08 9.74383056e-01]
 [3.70497927e-02 9.61320758e-01 1.62941683e-03]] 

predict index : [0 2 1]


In [8]:
grade = ['A', 'B', 'C']
arg_val = sess.run(tf.arg_max(pred_val, 1))
p_grade = [ grade[val] for val in arg_val ]
print(p_grade)

W0911 15:12:30.482521  5960 deprecation.py:323] From <ipython-input-8-578b74407afa>:2: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.math.argmax` instead


['A', 'C', 'B']


In [9]:
import tensorflow as tf

tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1], 
          [2, 1, 3, 2], 
          [3, 1, 3, 4], 
          [4, 1, 5, 5],
          [1, 7, 5, 5], 
          [1, 2, 5, 6], 
          [1, 6, 6, 6], 
          [1, 7, 7, 7]]

y_data = [[0, 0, 1], 
          [0, 0, 1], 
          [0, 0, 1], 
          [0, 1, 0],
          [0, 1, 0], 
          [0, 1, 0], 
          [1, 0, 0], 
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [10]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
        print("Step : {}, \t Cost : {}".format(step, sess.run(cost, feed_dict={X: x_data, Y: y_data})))


Step : 0, 	 Cost : 5.4190874099731445
Step : 200, 	 Cost : 0.546149492263794
Step : 400, 	 Cost : 0.4448033273220062
Step : 600, 	 Cost : 0.369295597076416
Step : 800, 	 Cost : 0.2984141707420349
Step : 1000, 	 Cost : 0.23387078940868378
Step : 1200, 	 Cost : 0.21112346649169922
Step : 1400, 	 Cost : 0.19283469021320343
Step : 1600, 	 Cost : 0.17738723754882812
Step : 1800, 	 Cost : 0.1641688346862793
Step : 2000, 	 Cost : 0.15273377299308777



In [11]:
all = sess.run(hypothesis, feed_dict={
               X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
print(all, '\n\n예측값 :', sess.run(tf.arg_max(all, 1)))

[[3.1222650e-03 9.9686629e-01 1.1442469e-05]
 [8.8555580e-01 9.5315114e-02 1.9129099e-02]
 [1.4553346e-08 3.3987936e-04 9.9966013e-01]] 

예측값 : [1 0 2]


In [12]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('./data/data-04-zoo.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)
print('\nx_data :\n', x_data)
print('\ny_data :\n', y_data)

nb_classes = 7  # 0 ~ 6

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])  # 0 ~ 6

Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
print("\none_hot", Y_one_hot)

Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("\nreshape", Y_one_hot)

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                 labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

(101, 16) (101, 1)

x_data :
 [[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]]

y_data :
 [[0.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [3.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [6.]
 [6.]
 [6.]
 [1.]
 [0.]
 [3.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [5.]
 [4.]
 [4.]
 [0.]
 [0.]
 [0.]
 [5.]
 [0.]
 [0.]
 [1.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [5.]
 [5.]
 [1.]
 [5.]
 [1.]
 [0.]
 [0.]
 [6.]
 [0.]
 [0.]
 [0.]
 [0.]
 [5.]
 [4.]
 [6.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [3.]
 [3.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [6.]
 [3.]
 [0.]
 [0.]
 [2.]
 [6.]
 [1.]
 [1.]
 [2.]
 [6.]
 [3.]
 [1.]
 [0.]
 [6.]
 [3.]
 [1.]
 [5.]
 [4.]
 [2.]
 [2.]
 [3.]
 [0.]
 [0.]
 [1.]
 [0.]
 [5.]
 [0.]
 [6.]
 [1.]]

one_hot Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)

reshape Tensor("Reshape:0", shape=(?, 7), dtype=float32)


W0911 15:18:14.920020  5960 deprecation.py:323] From <ipython-input-12-0e2e994fd3a4>:33: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [13]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2000):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        loss, acc = sess.run([cost, accuracy], feed_dict={
                             X: x_data, Y: y_data})
        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
            step, loss, acc))

Step:     0, 	 Loss: 4.505, 	 Acc: 41.58%
Step:   100, 	 Loss: 0.675, 	 Acc: 83.17%
Step:   200, 	 Loss: 0.407, 	 Acc: 87.13%
Step:   300, 	 Loss: 0.292, 	 Acc: 91.09%
Step:   400, 	 Loss: 0.226, 	 Acc: 94.06%
Step:   500, 	 Loss: 0.183, 	 Acc: 95.05%
Step:   600, 	 Loss: 0.153, 	 Acc: 96.04%
Step:   700, 	 Loss: 0.132, 	 Acc: 98.02%
Step:   800, 	 Loss: 0.115, 	 Acc: 100.00%
Step:   900, 	 Loss: 0.103, 	 Acc: 100.00%
Step:  1000, 	 Loss: 0.092, 	 Acc: 100.00%
Step:  1100, 	 Loss: 0.084, 	 Acc: 100.00%
Step:  1200, 	 Loss: 0.077, 	 Acc: 100.00%
Step:  1300, 	 Loss: 0.072, 	 Acc: 100.00%
Step:  1400, 	 Loss: 0.067, 	 Acc: 100.00%
Step:  1500, 	 Loss: 0.062, 	 Acc: 100.00%
Step:  1600, 	 Loss: 0.059, 	 Acc: 100.00%
Step:  1700, 	 Loss: 0.055, 	 Acc: 100.00%
Step:  1800, 	 Loss: 0.052, 	 Acc: 100.00%
Step:  1900, 	 Loss: 0.050, 	 Acc: 100.00%


In [14]:
pred = sess.run(prediction, feed_dict={X: x_data})

for p, y in zip(pred, y_data.flatten()):
    print('[{}]  Prediction : {},  True Y : {}'.format(p==int(y),p,int(y)))

[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 3,  True Y : 3
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 3,  True Y : 3
[True]  Prediction : 3,  True Y : 3
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 1,  True Y : 1
[True]  Prediction : 3,  True Y : 3
[True]  Prediction : 6,  True Y : 6
[True]  Prediction : 6,  True Y : 6
[True]  Prediction : 6,  True Y : 6
[True]  Prediction : 1,  True Y : 1
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 3,  True Y : 3
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 1,  True Y : 1
[True]  Prediction : 1,  True Y : 1
[True]  Prediction : 0,  True Y : 0
[True]  Prediction : 1,  True Y : 1
[True]  Prediction : 5,  True Y : 5
[True]  Prediction : 4,  True Y : 4
[True]  Prediction : 4,  True Y : 4
[True]  Prediction : 0,  Tru