In [1]:
import tensorflow as tf
tf.__version__

'1.14.0'

In [19]:
!pip install images

  ERROR: Could not find a version that satisfies the requirement images (from versions: none)
ERROR: No matching distribution found for images


In [21]:
from IPython.display import Image 
from tqdm import tqdm_notebook

In [5]:
tf.set_random_seed(777)  

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y  = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b  = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

Tensor("add_2:0", dtype=float32)


In [6]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})

    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))


Step : 0 
Cost : 62547.2890625 
Prediction :
[-75.96345  -78.27629  -83.83015  -90.80436  -56.976482]

Step : 1 
Cost : 19614.837890625 
Prediction :
[21.697487 39.10213  31.826246 35.14237  32.553165]

Step : 2 
Cost : 6157.78759765625 
Prediction :
[ 76.37489  104.817566  96.5782   105.65545   82.676956]

Step : 3 
Cost : 1939.7125244140625 
Prediction :
[106.9874  141.6088  132.83064 145.13327 110.73886]

Step : 4 
Cost : 617.5654907226562 
Prediction :
[124.12685 162.2064  153.12724 167.23558 126.44912]

Step : 5 
Cost : 203.13729858398438 
Prediction :
[133.72324 173.73782 164.49077 179.61    135.24416]

Step : 6 
Cost : 73.23114776611328 
Prediction :
[139.09654 180.1934  170.85298 186.5381  140.1676 ]

Step : 7 
Cost : 32.50749206542969 
Prediction :
[142.10548 183.8072  174.41512 190.41704 142.92351]

Step : 8 
Cost : 19.737699508666992 
Prediction :
[143.79071 185.82999 176.40964 192.58882 144.46584]

Step : 9 
Cost : 15.729873657226562 
Prediction :
[144.73486 186.96207 177.

In [7]:
tf.set_random_seed(777)  

x_data = [[73., 80., 75.], 
          [93., 88., 93.],
          [89., 91., 90.], 
          [96., 98., 100.], 
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})

    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))


Step : 0 
Cost : 126121.6015625 
Prediction :
[[-159.22546]
 [-197.2163 ]
 [-191.33363]
 [-208.02669]
 [-152.1618 ]]

Step : 1 
Cost : 39541.20703125 
Prediction :
[[-20.541216]
 [-30.525648]
 [-27.091803]
 [-29.171347]
 [-25.018284]]

Step : 2 
Cost : 12402.845703125 
Prediction :
[[57.102417]
 [62.79873 ]
 [64.86099 ]
 [70.96306 ]
 [46.165253]]

Step : 3 
Cost : 3896.40625 
Prediction :
[[100.57165 ]
 [115.04803 ]
 [116.34181 ]
 [127.02448 ]
 [ 86.018845]]

Step : 4 
Cost : 1230.0838623046875 
Prediction :
[[124.90789]
 [144.3009 ]
 [145.16386]
 [158.41109]
 [108.33195]]

Step : 5 
Cost : 394.32940673828125 
Prediction :
[[138.53227]
 [160.67891]
 [161.30006]
 [175.98314]
 [120.82479]]

Step : 6 
Cost : 132.3600311279297 
Prediction :
[[146.15947]
 [169.84877]
 [170.33398]
 [185.82094]
 [127.81961]]

Step : 7 
Cost : 50.24222946166992 
Prediction :
[[150.42906]
 [174.98302]
 [175.39154]
 [191.32861]
 [131.7363 ]]

Step : 8 
Cost : 24.497928619384766 
Prediction :
[[152.8189 ]
 [177.

In [10]:

import numpy as np

tf.set_random_seed(777)  

xy = np.loadtxt('./data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print("x_data.shape : {}, \tlen(x_data) : {} \nx_data : \n{}".format(x_data.shape, len(x_data), x_data))
print("-"*25)
print("y_data.shape : {}  \ny_data : \n{}".format(y_data.shape, y_data))

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

x_data.shape : (25, 3), 	len(x_data) : 25 
x_data : 
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
-------------------------
y_data.shape : (25, 1)  
y_data : 
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})

    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))


Step : 0 
Cost : 20682.216796875 
Prediction :
[[15.3530855]
 [25.620491 ]
 [21.435873 ]
 [23.021599 ]
 [21.901628 ]
 [17.103834 ]
 [15.216542 ]
 [ 8.105922 ]
 [25.533789 ]
 [23.99665  ]
 [17.138174 ]
 [20.137476 ]
 [22.434807 ]
 [19.68472  ]
 [16.372953 ]
 [25.100708 ]
 [21.371382 ]
 [16.114529 ]
 [20.338524 ]
 [17.508432 ]
 [18.731852 ]
 [23.45593  ]
 [17.350943 ]
 [16.195797 ]
 [25.42364  ]]

Step : 1 
Cost : 7661.43017578125 
Prediction :
[[68.32281 ]
 [89.28384 ]
 [84.165085]
 [91.338844]
 [70.45464 ]
 [52.900417]
 [66.35534 ]
 [46.018482]
 [85.03186 ]
 [79.10705 ]
 [66.40696 ]
 [68.71708 ]
 [87.24234 ]
 [73.55812 ]
 [67.74665 ]
 [89.70451 ]
 [72.67783 ]
 [77.48663 ]
 [82.12339 ]
 [72.79138 ]
 [78.69987 ]
 [83.181145]
 [74.525734]
 [69.60098 ]
 [91.40337 ]]

Step : 2 
Cost : 2847.277099609375 
Prediction :
[[100.53139 ]
 [127.994156]
 [122.30769 ]
 [132.87944 ]
 [ 99.9769  ]
 [ 74.66642 ]
 [ 97.45092 ]
 [ 69.07227 ]
 [121.20958 ]
 [112.61717 ]
 [ 96.36511 ]
 [ 98.255974]
 [126.64

 [192.87552]]

Step : 1300 
Cost : 15.094025611877441 
Prediction :
[[151.09898 ]
 [187.09114 ]
 [181.36497 ]
 [197.6614  ]
 [144.247   ]
 [107.8247  ]
 [147.10469 ]
 [107.557106]
 [176.61723 ]
 [164.81403 ]
 [143.22592 ]
 [143.89812 ]
 [187.15527 ]
 [155.83395 ]
 [148.66734 ]
 [189.55498 ]
 [149.9473  ]
 [175.07808 ]
 [177.56108 ]
 [158.45193 ]
 [172.98457 ]
 [175.4998  ]
 [164.42857 ]
 [151.89307 ]
 [192.81294 ]]

Step : 1400 
Cost : 14.664348602294922 
Prediction :
[[151.14029 ]
 [187.02838 ]
 [181.35873 ]
 [197.68327 ]
 [144.14752 ]
 [107.78246 ]
 [147.19525 ]
 [107.731285]
 [176.56755 ]
 [164.82135 ]
 [143.25018 ]
 [143.88345 ]
 [187.11731 ]
 [155.7536  ]
 [148.7447  ]
 [189.52908 ]
 [149.80098 ]
 [175.23099 ]
 [177.53763 ]
 [158.44832 ]
 [173.06444 ]
 [175.4762  ]
 [164.50604 ]
 [151.86246 ]
 [192.75195 ]]

Step : 1500 
Cost : 14.25606918334961 
Prediction :
[[151.18088]
 [186.96709]
 [181.35278]
 [197.70462]
 [144.0504 ]
 [107.7409 ]
 [147.28351]
 [107.90099]
 [176.51869]
 [164.

In [12]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})

    if step % 100 == 0 or step < 10 :
        print("Step : {} \tCost : {} ".format(step, cost_val))
        

Step : 0 	Cost : 20682.216796875 
Step : 1 	Cost : 7661.43017578125 
Step : 2 	Cost : 2847.277099609375 
Step : 3 	Cost : 1067.34716796875 
Step : 4 	Cost : 409.25250244140625 
Step : 5 	Cost : 165.9315185546875 
Step : 6 	Cost : 75.96328735351562 
Step : 7 	Cost : 42.6942138671875 
Step : 8 	Cost : 30.388269424438477 
Step : 9 	Cost : 25.833059310913086 
Step : 100 	Cost : 22.404691696166992 
Step : 200 	Cost : 21.608549118041992 
Step : 300 	Cost : 20.8525447845459 
Step : 400 	Cost : 20.134559631347656 
Step : 500 	Cost : 19.452693939208984 
Step : 600 	Cost : 18.805055618286133 
Step : 700 	Cost : 18.18989372253418 
Step : 800 	Cost : 17.605554580688477 
Step : 900 	Cost : 17.050495147705078 
Step : 1000 	Cost : 16.523174285888672 
Step : 1100 	Cost : 16.0222110748291 
Step : 1200 	Cost : 15.546247482299805 
Step : 1300 	Cost : 15.094025611877441 
Step : 1400 	Cost : 14.664348602294922 
Step : 1500 	Cost : 14.25606918334961 
Step : 1600 	Cost : 13.868073463439941 
Step : 1700 	Cost

In [13]:
print("Your score \t: \n", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score 	: 
 [[194.89839]]


In [14]:
print("\nOther scores \t: \n", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Other scores 	: 
 [[165.0794 ]
 [176.52182]]


In [15]:
tf.set_random_seed(777) 

filename_queue = tf.train.string_input_producer(
    ['./data/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

W0911 11:03:48.395267  6232 deprecation.py:323] From <ipython-input-15-24712a802733>:4: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0911 11:03:48.406013  6232 deprecation.py:323] From C:\Python\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0911 11:03:48.407919  623

In [16]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

Step_val = []
Cost_val = []

for step in tqdm_notebook(range(2001)):

    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    

    Step_val.append(step)
    Cost_val.append(cost_val)
    
    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))

coord.request_stop()
coord.join(threads)

W0911 11:04:07.151655  6232 deprecation.py:323] From <ipython-input-16-28d728473fd2>:5: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.



Step : 0 
Cost : 30978.400390625 
Prediction :
[[-10.5520935]
 [-18.421577 ]
 [-14.914436 ]
 [-19.039238 ]
 [-13.2786255]
 [-14.993626 ]
 [-16.968872 ]
 [-16.157917 ]
 [-22.078262 ]
 [-27.293266 ]]

Step : 1 
Cost : 12231.3759765625 
Prediction :
[[43.16722 ]
 [38.92281 ]
 [64.13846 ]
 [56.88572 ]
 [42.62716 ]
 [55.684196]
 [55.79019 ]
 [51.981804]
 [62.46227 ]
 [55.94705 ]]

Step : 2 
Cost : 5287.12353515625 
Prediction :
[[ 97.59089 ]
 [ 97.0528  ]
 [ 94.32073 ]
 [100.271095]
 [112.16209 ]
 [ 92.96686 ]
 [106.03886 ]
 [107.69688 ]
 [114.504074]
 [ 81.644264]]

Step : 3 
Cost : 1493.1212158203125 
Prediction :
[[ 74.055824]
 [110.207405]
 [ 78.125465]
 [125.918816]
 [109.81078 ]
 [107.33985 ]
 [102.183716]
 [148.57176 ]
 [127.08399 ]
 [109.53553 ]]

Step : 4 
Cost : 783.9133911132812 
Prediction :
[[155.31958]
 [134.9293 ]
 [146.63405]
 [157.76044]
 [141.21684]
 [143.87987]
 [143.15866]
 [138.45131]
 [141.47476]
 [163.08902]]

Step : 5 
Cost : 321.26654052734375 
Prediction :
[[144.1

In [17]:
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [12,6]
plt.plot(Step_val, Cost_val)
plt.title('cost function')
plt.xlabel('step')
plt.ylabel('cost')
plt.xlim(0,10)
plt.show()

<Figure size 1200x600 with 1 Axes>